// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: audiosvc.proto

package audio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AudioClient is the client API for Audio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadReply, error)
}

type audioClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioClient(cc grpc.ClientConnInterface) AudioClient {
	return &audioClient{cc}
}

func (c *audioClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/pb.Audio/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadReply, error) {
	out := new(UploadReply)
	err := c.cc.Invoke(ctx, "/pb.Audio/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioServer is the server API for Audio service.
// All implementations must embed UnimplementedAudioServer
// for forward compatibility
type AudioServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
	Upload(context.Context, *UploadRequest) (*UploadReply, error)
	// mustEmbedUnimplementedAudioServer()
}

// UnimplementedAudioServer must be embedded to have forward compatible implementations.
type UnimplementedAudioServer struct {
	
}

func (UnimplementedAudioServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAudioServer) Upload(context.Context, *UploadRequest) (*UploadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedAudioServer) mustEmbedUnimplementedAudioServer() {}

// UnsafeAudioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServer will
// result in compilation errors.
type UnsafeAudioServer interface {
	mustEmbedUnimplementedAudioServer()
}

func RegisterAudioServer(s grpc.ServiceRegistrar, srv AudioServer) {
	s.RegisterService(&Audio_ServiceDesc, srv)
}

func _Audio_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Audio/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Audio_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Audio/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Audio_ServiceDesc is the grpc.ServiceDesc for Audio service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Audio_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Audio",
	HandlerType: (*AudioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Audio_Get_Handler,
		},
		{
			MethodName: "Upload",
			Handler:    _Audio_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audiosvc.proto",
}
